### ISSUE TITLE
コードブロックの横幅よりコードが長くなる場合に表示されない

### ISSUE THREAD

**Issue by eno1220** [kss-pc-club/book-2023#13]
<img width="653" alt="スクリーンショット 2023-05-19 午後7 18 12" src="https://github.com/kss-pc-club/book-2023/assets/86103453/bed965eb-95c8-407c-821e-f6cf60a69120">

コードブロックの横幅より、コードが長くなる場合に表示されません。（スクリーンショットはPDF版です）
28ae48dee2fe2e5d6cd139d141f66b2e20dc2735

**Comment by Ryoga-exe** [comment]
word-wrap をあてると良いです

https://developer.mozilla.org/ja/docs/Web/CSS/word-break

**Comment by eno1220** [comment]
解決には至りませんでした...

**Comment by Ryoga-exe** [comment]
うーん、去年はこれで直ったのだけど…

https://github.com/kss-pc-club/book-2022/commit/e6a210e2a697b30d3ecd79b22387dcd5ca0b626a

**Comment by eno1220** [comment]
#25 でおそらく対応できていると思います。確認をお願いします。
